AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  postImages:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: postImages/
      Handler: post-images.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::921297957993:role/lambda-dynamodb-role'
      Environment:
        Variables:
          BUCKET_NAME: photos-nishikei
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: post
            
  getImages:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: getImages/
      Handler: get-images.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::921297957993:role/lambda-dynamodb-role'
      Runtime: python3.6
      Timeout: 3
      Environment:
        Variables:
          BUCKET_NAME: photos-nishikei
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: /images
            Method: get
  getImageById:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: getImageById/
      Handler: get-image-by-id.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::921297957993:role/lambda-dynamodb-role'
      Runtime: python3.6
      Timeout: 3
      Environment:
        Variables:
          BUCKET_NAME: photos-nishikei
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: '/images/{id}'
            Method: get
  deleteImageById:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: deleteImageById/
      Handler: delete-image-by-id.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::921297957993:role/lambda-dynamodb-role'
      Runtime: python3.6
      Timeout: 3
      Environment:
        Variables:
          BUCKET_NAME: photos-nishikei
          TABLE_NAME: photos
      Events:
        Api:
          Type: Api
          Properties:
            Path: '/images/{id}'
            Method: delete
  updateImage:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      CodeUri: updateImage/
      Handler: update-image.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 15
      Role: 'arn:aws:iam::921297957993:role/lambda-dynamodb-role'
      Environment:
        Variables:
          BUCKET_NAME: photos-nishikei
          TABLE_NAME: photos
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: '/images'
            Method: PUT